Better error handling, allow setting of branch
If no branch is checked out, then we won't know which ref to push things
to.
Allow overriding the branch, and error out when it's not.

diff --git a/qtdev/git-gpush b/qtdev/git-gpush
--- a/qtdev/git-gpush
+++ b/qtdev/git-gpush
@@ -1,7 +1,23 @@
 #!/bin/bash
 
-sha="$*"
 branch=$(git branch --show-current --no-color)
+
+case "$1" in
+  --branch)
+    shift
+    branch=$1
+    shift
+    ;;
+esac
+
+if [ -z "$branch" ]
+then
+    >&2 echo "fatal: Can't identify which branch to push to"
+    exit 1
+fi
+
+sha="$*"
+
 remote="origin"
 repository=$(git rev-parse --git-dir)
 repository=${repository%/\.git/worktrees*}
